/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_sovworks_eds_crypto_LocalEncryptedFileXTS */

#ifndef _Included_com_sovworks_eds_crypto_LocalEncryptedFileXTS
#define _Included_com_sovworks_eds_crypto_LocalEncryptedFileXTS
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_sovworks_eds_crypto_LocalEncryptedFileXTS
 * Method:    flush
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_com_sovworks_eds_crypto_LocalEncryptedFileXTS_flush
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_sovworks_eds_crypto_LocalEncryptedFileXTS
 * Method:    close
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_com_sovworks_eds_crypto_LocalEncryptedFileXTS_close
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_sovworks_eds_crypto_LocalEncryptedFileXTS
 * Method:    getPosition
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_com_sovworks_eds_crypto_LocalEncryptedFileXTS_getPosition
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_sovworks_eds_crypto_LocalEncryptedFileXTS
 * Method:    seek
 * Signature: (JJ)V
 */
JNIEXPORT void JNICALL Java_com_sovworks_eds_crypto_LocalEncryptedFileXTS_seek
  (JNIEnv *, jclass, jlong, jlong);

/*
 * Class:     com_sovworks_eds_crypto_LocalEncryptedFileXTS
 * Method:    ftruncate
 * Signature: (JJ)I
 */
JNIEXPORT jint JNICALL Java_com_sovworks_eds_crypto_LocalEncryptedFileXTS_ftruncate
  (JNIEnv *, jclass, jlong, jlong);

/*
 * Class:     com_sovworks_eds_crypto_LocalEncryptedFileXTS
 * Method:    initContext
 * Signature: (Ljava/lang/String;ZJ)J
 */
JNIEXPORT jlong JNICALL Java_com_sovworks_eds_crypto_LocalEncryptedFileXTS_initContext
  (JNIEnv *, jclass, jstring, jboolean, jlong);

/*
 * Class:     com_sovworks_eds_crypto_LocalEncryptedFileXTS
 * Method:    read
 * Signature: (J[BII)I
 */
JNIEXPORT jint JNICALL Java_com_sovworks_eds_crypto_LocalEncryptedFileXTS_read
  (JNIEnv *, jclass, jlong, jbyteArray, jint, jint);

/*
 * Class:     com_sovworks_eds_crypto_LocalEncryptedFileXTS
 * Method:    write
 * Signature: (J[BII)I
 */
JNIEXPORT jint JNICALL Java_com_sovworks_eds_crypto_LocalEncryptedFileXTS_write
  (JNIEnv *, jclass, jlong, jbyteArray, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
