/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_sovworks_eds_crypto_Serpent */

#ifndef _Included_com_sovworks_eds_crypto_Serpent
#define _Included_com_sovworks_eds_crypto_Serpent
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_sovworks_eds_crypto_Serpent
 * Method:    initContext
 * Signature: ([B)J
 */
JNIEXPORT jlong JNICALL Java_com_sovworks_eds_crypto_Serpent_initContext
  (JNIEnv *, jobject, jbyteArray);

/*
 * Class:     com_sovworks_eds_crypto_Serpent
 * Method:    closeContext
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_com_sovworks_eds_crypto_Serpent_closeContext
  (JNIEnv *, jobject, jlong);

/*
 * Class:     com_sovworks_eds_crypto_Serpent
 * Method:    encrypt
 * Signature: ([BJ)V
 */
JNIEXPORT void JNICALL Java_com_sovworks_eds_crypto_Serpent_encrypt
  (JNIEnv *, jobject, jbyteArray, jlong);

/*
 * Class:     com_sovworks_eds_crypto_Serpent
 * Method:    decrypt
 * Signature: ([BJ)V
 */
JNIEXPORT void JNICALL Java_com_sovworks_eds_crypto_Serpent_decrypt
  (JNIEnv *, jobject, jbyteArray, jlong);

#ifdef __cplusplus
}
#endif
#endif
