/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_sovworks_eds_crypto_CBC */

#ifndef _Included_com_sovworks_eds_crypto_CBC
#define _Included_com_sovworks_eds_crypto_CBC
#ifdef __cplusplus
extern "C" {
#endif
#undef com_sovworks_eds_crypto_CBC_SECTOR_SIZE
#define com_sovworks_eds_crypto_CBC_SECTOR_SIZE 512L
/*
 * Class:     com_sovworks_eds_crypto_CBC
 * Method:    initContext
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_com_sovworks_eds_crypto_CBC_initContext
  (JNIEnv *, jobject);

/*
 * Class:     com_sovworks_eds_crypto_CBC
 * Method:    closeContext
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_com_sovworks_eds_crypto_CBC_closeContext
  (JNIEnv *, jobject, jlong);

/*
 * Class:     com_sovworks_eds_crypto_CBC
 * Method:    attachNativeCipher
 * Signature: (JJ)V
 */
JNIEXPORT void JNICALL Java_com_sovworks_eds_crypto_CBC_attachNativeCipher
  (JNIEnv *, jobject, jlong, jlong);

/*
 * Class:     com_sovworks_eds_crypto_CBC
 * Method:    encrypt
 * Signature: ([BII[BJ)I
 */
JNIEXPORT jint JNICALL Java_com_sovworks_eds_crypto_CBC_encrypt
  (JNIEnv *, jobject, jbyteArray, jint, jint, jbyteArray, jlong, jboolean);

/*
 * Class:     com_sovworks_eds_crypto_CBC
 * Method:    decrypt
 * Signature: ([BII[BJ)I
 */
JNIEXPORT jint JNICALL Java_com_sovworks_eds_crypto_CBC_decrypt
  (JNIEnv *, jobject, jbyteArray, jint, jint, jbyteArray, jlong, jboolean);

#ifdef __cplusplus
}
#endif
#endif
