/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_sovworks_eds_fs_util_FDRandomAccessIO */

#ifndef _Included_com_sovworks_eds_fs_util_FDRandomAccessIO
#define _Included_com_sovworks_eds_fs_util_FDRandomAccessIO
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_sovworks_eds_fs_util_FDRandomAccessIO
 * Method:    flush
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_com_sovworks_eds_fs_util_FDRandomAccessIO_flush
  (JNIEnv *, jclass, jint);

/*
 * Class:     com_sovworks_eds_fs_util_FDRandomAccessIO
 * Method:    getSize
 * Signature: (I)J
 */
JNIEXPORT jlong JNICALL Java_com_sovworks_eds_fs_util_FDRandomAccessIO_getSize
  (JNIEnv *, jclass, jint);

/*
 * Class:     com_sovworks_eds_fs_util_FDRandomAccessIO
 * Method:    close
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_com_sovworks_eds_fs_util_FDRandomAccessIO_close
  (JNIEnv *, jclass, jint);

/*
 * Class:     com_sovworks_eds_fs_util_FDRandomAccessIO
 * Method:    getPosition
 * Signature: (I)J
 */
JNIEXPORT jlong JNICALL Java_com_sovworks_eds_fs_util_FDRandomAccessIO_getPosition
  (JNIEnv *, jclass, jint);

/*
 * Class:     com_sovworks_eds_fs_util_FDRandomAccessIO
 * Method:    seek
 * Signature: (IJ)V
 */
JNIEXPORT void JNICALL Java_com_sovworks_eds_fs_util_FDRandomAccessIO_seek
  (JNIEnv *, jclass, jint, jlong);

/*
 * Class:     com_sovworks_eds_fs_util_FDRandomAccessIO
 * Method:    ftruncate
 * Signature: (IJ)I
 */
JNIEXPORT jint JNICALL Java_com_sovworks_eds_fs_util_FDRandomAccessIO_ftruncate
  (JNIEnv *, jclass, jint, jlong);

/*
 * Class:     com_sovworks_eds_fs_util_FDRandomAccessIO
 * Method:    read
 * Signature: (I[BII)I
 */
JNIEXPORT jint JNICALL Java_com_sovworks_eds_fs_util_FDRandomAccessIO_read
  (JNIEnv *, jclass, jint, jbyteArray, jint, jint);

/*
 * Class:     com_sovworks_eds_fs_util_FDRandomAccessIO
 * Method:    write
 * Signature: (I[BII)I
 */
JNIEXPORT jint JNICALL Java_com_sovworks_eds_fs_util_FDRandomAccessIO_write
  (JNIEnv *, jclass, jint, jbyteArray, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
