/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_sovworks_eds_crypto_GOST */

#ifndef _Included_com_sovworks_eds_crypto_GOST
#define _Included_com_sovworks_eds_crypto_GOST
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_sovworks_eds_crypto_GOST
 * Method:    initContext
 * Signature: ([B)J
 */
JNIEXPORT jlong JNICALL Java_com_sovworks_eds_crypto_GOST_initContext
  (JNIEnv *, jobject, jbyteArray);

/*
 * Class:     com_sovworks_eds_crypto_GOST
 * Method:    closeContext
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_com_sovworks_eds_crypto_GOST_closeContext
  (JNIEnv *, jobject, jlong);

/*
 * Class:     com_sovworks_eds_crypto_GOST
 * Method:    encrypt
 * Signature: ([BJ)V
 */
JNIEXPORT void JNICALL Java_com_sovworks_eds_crypto_GOST_encrypt
  (JNIEnv *, jobject, jbyteArray, jlong);

/*
 * Class:     com_sovworks_eds_crypto_GOST
 * Method:    decrypt
 * Signature: ([BJ)V
 */
JNIEXPORT void JNICALL Java_com_sovworks_eds_crypto_GOST_decrypt
  (JNIEnv *, jobject, jbyteArray, jlong);

#ifdef __cplusplus
}
#endif
#endif
