/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_sovworks_eds_crypto_CFB */

#ifndef _Included_com_sovworks_eds_crypto_CFB
#define _Included_com_sovworks_eds_crypto_CFB
#ifdef __cplusplus
extern "C" {
#endif
#undef com_sovworks_eds_crypto_CFB_SECTOR_SIZE
#define com_sovworks_eds_crypto_CFB_SECTOR_SIZE 512L
/*
 * Class:     com_sovworks_eds_crypto_CFB
 * Method:    initContext
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_com_sovworks_eds_crypto_CFB_initContext
  (JNIEnv *, jobject);

/*
 * Class:     com_sovworks_eds_crypto_CFB
 * Method:    closeContext
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_com_sovworks_eds_crypto_CFB_closeContext
  (JNIEnv *, jobject, jlong);

/*
 * Class:     com_sovworks_eds_crypto_CFB
 * Method:    attachNativeCipher
 * Signature: (JJ)V
 */
JNIEXPORT void JNICALL Java_com_sovworks_eds_crypto_CFB_attachNativeCipher
  (JNIEnv *, jobject, jlong, jlong);

/*
 * Class:     com_sovworks_eds_crypto_CFB
 * Method:    encrypt
 * Signature: ([BII[BJ)I
 */
JNIEXPORT jint JNICALL Java_com_sovworks_eds_crypto_CFB_encrypt
  (JNIEnv *, jobject, jbyteArray, jint, jint, jbyteArray, jlong);

/*
 * Class:     com_sovworks_eds_crypto_CFB
 * Method:    decrypt
 * Signature: ([BII[BJ)I
 */
JNIEXPORT jint JNICALL Java_com_sovworks_eds_crypto_CFB_decrypt
  (JNIEnv *, jobject, jbyteArray, jint, jint, jbyteArray, jlong);

#ifdef __cplusplus
}
#endif
#endif
